-- Migration: Create cash_movements table for financial tracking
-- This table stores all income and expense movements

-- Create cash_movements table
create table if not exists cash_movements (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Movement type
  type text not null check (type in ('income', 'expense')),
  
  -- Category for classification
  category text not null check (category in (
    'appointment',    -- Ingreso por cita
    'tip',            -- Propina
    'product_sale',   -- Venta de producto
    'rent',           -- Alquiler
    'supplies',       -- Insumos
    'utilities',      -- Servicios (luz, agua, etc)
    'salary',         -- Salarios
    'marketing',      -- Marketing/Publicidad
    'maintenance',    -- Mantenimiento
    'other'           -- Otro
  )),
  
  -- Amount (always positive, type determines if income/expense)
  amount numeric not null check (amount > 0),
  
  -- Description
  description text,
  
  -- Optional link to appointment (for automatic income)
  appointment_id bigint references appointments(id) on delete set null,
  
  -- Date of the movement (can be different from created_at for manual entries)
  movement_date date default current_date not null
);

-- Enable RLS
alter table cash_movements enable row level security;

-- Drop and recreate policies (idempotent)
drop policy if exists "Authenticated can read cash_movements" on cash_movements;
drop policy if exists "Authenticated can manage cash_movements" on cash_movements;

-- Allow authenticated users to read all movements
create policy "Authenticated can read cash_movements"
  on cash_movements for select
  to authenticated
  using (true);

-- Allow authenticated users to insert/update/delete movements
create policy "Authenticated can manage cash_movements"
  on cash_movements for all
  to authenticated
  using (true);

-- Create indexes for faster queries
create index if not exists idx_cash_movements_date on cash_movements(movement_date);
create index if not exists idx_cash_movements_type on cash_movements(type);
create index if not exists idx_cash_movements_category on cash_movements(category);
