-- Migration: Create clients table for CRM
-- This table stores client information with loyalty and no-show tracking

-- Create clients table
create table if not exists clients (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Basic info
  name text not null,
  phone text unique,
  email text,
  avatar_url text, -- Optional client photo
  
  -- Stats (auto-calculated)
  total_visits integer default 0,
  total_spent numeric default 0,
  
  -- Loyalty program
  loyalty_points integer default 0,
  
  -- No-show tracking
  no_show_count integer default 0,
  
  -- Metadata
  last_visit timestamp with time zone,
  notes text
);

-- Enable RLS
alter table clients enable row level security;

-- Drop and recreate policies (idempotent)
drop policy if exists "Authenticated can read clients" on clients;
drop policy if exists "Authenticated can manage clients" on clients;

-- Allow authenticated users to read all clients
create policy "Authenticated can read clients"
  on clients for select
  to authenticated
  using (true);

-- Allow authenticated users to insert/update/delete clients
create policy "Authenticated can manage clients"
  on clients for all
  to authenticated
  using (true);

-- Create index for faster phone lookups (for WhatsApp integration)
create index if not exists idx_clients_phone on clients(phone);

-- Add avatar_url column if it doesn't exist (for existing tables)
alter table clients add column if not exists avatar_url text;
alter table clients add column if not exists notes text;

-- Add client_id foreign key to appointments table (if not exists)
-- This links appointments to clients for tracking history
alter table appointments 
  add column if not exists client_id bigint references clients(id);

-- Create function to auto-update client stats after appointment completion
create or replace function update_client_stats()
returns trigger as $$
begin
  -- Only update if appointment is completed and has a client_id
  if NEW.status = 'completed' and NEW.client_id is not null then
    update clients 
    set 
      total_visits = total_visits + 1,
      total_spent = total_spent + coalesce(NEW.price, 0),
      last_visit = NEW.appointment_date,
      -- Add loyalty point for each completed visit
      loyalty_points = loyalty_points + 1
    where id = NEW.client_id;
  end if;
  
  -- Track no-shows
  if NEW.status = 'cancelled' and OLD.status != 'cancelled' and NEW.client_id is not null then
    update clients 
    set no_show_count = no_show_count + 1
    where id = NEW.client_id;
  end if;
  
  return NEW;
end;
$$ language plpgsql;

-- Create trigger to update client stats
drop trigger if exists on_appointment_update_client_stats on appointments;
create trigger on_appointment_update_client_stats
  after update on appointments
  for each row
  execute function update_client_stats();
