-- 1. Agregar columna 'price' a la tabla appointments si no existe
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'appointments' AND column_name = 'price') THEN
        ALTER TABLE appointments ADD COLUMN price numeric;
    END IF;
END $$;

-- 2. Crear tabla services si no existe
CREATE TABLE IF NOT EXISTS services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  duration_minutes integer default 30,
  image_url text
);

-- 3. Habilitar RLS en services
ALTER TABLE services ENABLE ROW LEVEL SECURITY;

-- 4. Recrear Políticas para Services (usamos DO block para evitar error si ya existen)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'services' AND policyname = 'Public read services') THEN
        CREATE POLICY "Public read services" ON services FOR SELECT TO anon USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'services' AND policyname = 'Admin all services') THEN
        CREATE POLICY "Admin all services" ON services FOR ALL TO authenticated USING (true);
    END IF;
END $$;

-- 5. Insertar datos iniciales SOLO si la tabla está vacía
INSERT INTO services (name, price, duration_minutes)
SELECT 'Corte de Cabello', 15.00, 30
WHERE NOT EXISTS (SELECT 1 FROM services);

INSERT INTO services (name, price, duration_minutes)
SELECT 'Barba', 10.00, 20
WHERE NOT EXISTS (SELECT 1 FROM services WHERE name = 'Barba');

INSERT INTO services (name, price, duration_minutes)
SELECT 'Corte + Barba', 22.00, 50
WHERE NOT EXISTS (SELECT 1 FROM services WHERE name = 'Corte + Barba');

INSERT INTO services (name, price, duration_minutes)
SELECT 'Coloración', 35.00, 90
WHERE NOT EXISTS (SELECT 1 FROM services WHERE name = 'Coloración');
