-- Migration: Create products table for inventory management
-- This table stores product inventory with stock tracking

-- Create products table
create table if not exists products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Product info
  name text not null,
  description text,
  
  -- Pricing
  cost_price numeric default 0, -- Precio de costo
  sale_price numeric default 0, -- Precio de venta
  
  -- Stock
  stock integer default 0,
  min_stock integer default 5, -- Alerta cuando stock < min_stock
  
  -- Category
  category text check (category in (
    'hair_product',     -- Productos para cabello
    'beard_product',    -- Productos para barba
    'tools',            -- Herramientas
    'consumables',      -- Consumibles (toallas, etc)
    'other'             -- Otro
  )) default 'other',
  
  -- Status
  is_active boolean default true
);

-- Enable RLS
alter table products enable row level security;

-- Drop and recreate policies (idempotent)
drop policy if exists "Authenticated can read products" on products;
drop policy if exists "Authenticated can manage products" on products;

-- Allow authenticated users to read all products
create policy "Authenticated can read products"
  on products for select
  to authenticated
  using (true);

-- Allow authenticated users to insert/update/delete products
create policy "Authenticated can manage products"
  on products for all
  to authenticated
  using (true);

-- Create indexes
create index if not exists idx_products_category on products(category);
create index if not exists idx_products_stock on products(stock);
