-- Create appointments table
create table appointments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  client_phone text,
  client_email text,
  appointment_date timestamp with time zone not null,
  status text default 'pending' check (status in ('pending', 'confirmed', 'cancelled', 'completed')),
  service_type text,
  notes text,
  price numeric -- New field to store the price at the time of booking
);

-- Enable Row Level Security (RLS)
alter table appointments enable row level security;

-- Policy: Allow public to insert appointments (for the booking form)
create policy "Allow public inserts"
  on appointments for insert
  to anon
  with check (true);

-- Policy: Allow authenticated users (barbers) to view all appointments
create policy "Allow authenticated view"
  on appointments for select
  to authenticated
  using (true);

-- Policy: Allow authenticated users to update appointments (e.g., change status)
create policy "Allow authenticated update"
  on appointments for update
  to authenticated
  using (true);

-- Services Table
create table services (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  duration_minutes integer default 30,
  image_url text
);

alter table services enable row level security;

-- Public read access for services (so booking form can list them)
create policy "Public read services"
  on services for select
  to anon
  using (true);

-- Authenticated full access for services (admin management)
create policy "Admin all services"
  on services for all
  to authenticated
  using (true);

-- Seed initial data
insert into services (name, price, duration_minutes) values
  ('Corte de Cabello', 15.00, 30),
  ('Barba', 10.00, 20),
  ('Corte + Barba', 22.00, 50),
  ('Coloración', 35.00, 90);
