-- Migration: Settings and Custom Categories
-- This creates tables for custom categories and reminder settings

-- Custom categories table (for products, expenses, services)
create table if not exists custom_categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Category type (which entity this category belongs to)
  type text not null check (type in ('product', 'expense', 'income', 'service')),
  
  -- Category details
  name text not null,
  icon text, -- optional icon name
  color text, -- optional hex color
  
  -- Status
  is_active boolean default true,
  
  -- Order for display
  display_order integer default 0
);

-- Reminder settings table
create table if not exists reminder_settings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Reminder type
  type text not null check (type in ('appointment_confirmation', 'appointment_reminder', 'follow_up', 'promotion')),
  
  -- Is this reminder enabled?
  is_enabled boolean default true,
  
  -- Message template with placeholders like {client_name}, {date}, {time}
  message_template text not null,
  
  -- When to send (for appointment reminders)
  hours_before integer default 24, -- hours before appointment to send reminder
  
  -- Day/time for recurring reminders (for promotions)
  send_day text check (send_day in ('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday')),
  send_time time,
  
  -- Unique constraint per type
  unique(type)
);

-- Enable RLS
alter table custom_categories enable row level security;
alter table reminder_settings enable row level security;

-- Drop and recreate policies (idempotent)
drop policy if exists "Authenticated can read custom_categories" on custom_categories;
drop policy if exists "Authenticated can manage custom_categories" on custom_categories;
drop policy if exists "Authenticated can read reminder_settings" on reminder_settings;
drop policy if exists "Authenticated can manage reminder_settings" on reminder_settings;

-- Policies for custom_categories
create policy "Authenticated can read custom_categories"
  on custom_categories for select
  to authenticated
  using (true);

create policy "Authenticated can manage custom_categories"
  on custom_categories for all
  to authenticated
  using (true);

-- Policies for reminder_settings
create policy "Authenticated can read reminder_settings"
  on reminder_settings for select
  to authenticated
  using (true);

create policy "Authenticated can manage reminder_settings"
  on reminder_settings for all
  to authenticated
  using (true);

-- Create indexes
create index if not exists idx_custom_categories_type on custom_categories(type);

-- Insert default reminder templates
insert into reminder_settings (type, message_template, hours_before, is_enabled)
values 
  ('appointment_confirmation', 'Hola {client_name}! 👋 Por favor confirma tu cita para el {date} a las {time}. Responde SI para confirmar. ✂️', 48, true),
  ('appointment_reminder', 'Hola {client_name}! 📅 Te recordamos que tienes una cita mañana {date} a las {time}. ¡Te esperamos! ✂️', 24, true),
  ('follow_up', 'Hola {client_name}! ¿Cómo quedó tu corte? 💈 Esperamos verte pronto de nuevo. Agenda tu próxima cita!', 0, false)
on conflict (type) do nothing;
